spring:
  profiles:
    active: dev
    include:
      - swagger
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:mem:vehicledb
    username: admin
    password:
    hikari:
      pool-name: Hikari
      auto-commit: false
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
