create table driver (
    id bigint generated by default as identity,
--     created_by varchar(255) not null,
--     created_date timestamp not null,
--     updated_by varchar(255) not null,
--     updated_date timestamp not null,
    date_of_birth timestamp not null,
    name varchar(255) not null,
    primary key (id)
);

create table vehicle (
    id bigint generated by default as identity,
--     created_by varchar(255) not null,
--     created_date timestamp not null,
--     updated_by varchar(255) not null,
--     updated_date timestamp not null,
    brand varchar(255) not null,
    model varchar(255) not null,
    odo integer default 0,
    plate_number varchar(255),
    construction_year integer not null,
    driver_id bigint,
    primary key (id)
);
alter table vehicle add constraint fk_driver foreign key (driver_id) references driver;
