create table credential (
    id bigint generated by default as identity, 
    created_by varchar(255) not null, 
    created_date timestamp not null, 
    active boolean, pass_word varchar(255), 
    roles varchar(255), 
    user_name varchar(255), 
    driver_id bigint, 
    primary key (id)
);

create table driver (
    id bigint generated by default as identity, 
    created_by varchar(255) not null, 
    created_date timestamp not null, 
    date_of_birth timestamp not null, 
    name varchar(255) not null, 
    primary key (id)
);

create table payment_detail (
    driver_id bigint not null, 
    payment_id bigint not null, 
    business_man varchar(255), 
    primary key (payment_id, driver_id)
);

create table payment_history (
    id bigint generated by default as identity, 
    created_by varchar(255) not null, 
    created_date timestamp not null, 
    cost double, 
    status varchar(255), 
    vehicle_id bigint, 
    primary key (id)
);

create table vehicle (
    id bigint generated by default as identity, 
    created_by varchar(255) not null, 
    created_date timestamp not null, 
    brand varchar(255) not null, 
    model varchar(255) not null, 
    odo integer default 0, 
    plate_number varchar(255), 
    status varchar(255), 
    construction_year integer not null, 
    driver_id bigint, 
    primary key (id)
);

alter table credential drop constraint if exists uk_username;
alter table credential add constraint uk_username unique (user_name);
alter table credential drop constraint if exists uk_driver_id;
alter table credential add constraint uk_driver_id unique (driver_id);
alter table credential add constraint fk_credential_driver_id foreign key (driver_id) references driver;
alter table payment_detail add constraint fk_pd_driver_id foreign key (driver_id) references driver;
alter table payment_detail add constraint fk_pd_payment_id foreign key (payment_id) references payment_history;
alter table payment_history add constraint fk_ph_vehicle_id foreign key (vehicle_id) references vehicle;
alter table vehicle add constraint fk_vehicle_driver_id foreign key (driver_id) references driver;
