create table driver (
    id bigint generated by default as identity,
--     created_by varchar(255) not null,
--     created_date timestamp not null,
--     updated_by varchar(255) not null,
--     updated_date timestamp not null,
    date_of_birth timestamp not null,
    name varchar(255) not null,
    primary key (id)
);

create table payment_detail (
    driver_id bigint not null,
    payment_id bigint not null,
    business_man varchar(255),
    transaction_id binary not null,
    primary key (payment_id, driver_id)
);

create table payment_history (
    id bigint generated by default as identity,
    status varchar(255),
    primary key (id)
);

create table vehicle (
    id bigint generated by default as identity,
--     created_by varchar(255) not null,
--     created_date timestamp not null,
--     updated_by varchar(255) not null,
--     updated_date timestamp not null,
    brand varchar(255) not null,
    model varchar(255) not null,
    odo integer default 0,
    plate_number varchar(255),
    construction_year integer not null,
    driver_id bigint,
    primary key (id)
);

alter table payment_detail add constraint fk_driver_payment foreign key (driver_id) references driver;
alter table payment_detail add constraint fk_payment_driver foreign key (payment_id) references payment_history;
alter table vehicle add constraint fk_driver foreign key (driver_id) references driver;
alter table payment_detail drop constraint if exists payment_transaction_id;
alter table payment_detail add constraint payment_transaction_id unique (transaction_id);
